### ISSUE TITLE
Certain graphics (like elevator) appear on game map

### ISSUE THREAD

**Issue by Jareth247** [Mikejmoffitt/LICS#1] opened 2017-03-05 05:31 UTC
Whenever I pause the game on a screen with certain objects, like the elevator and the "Under Construction" graphic that damages you, then that item appears on the map on the pause menu. I've only run it on my Raspberry Pi, running Retro Pie. I can't remember if I was running the latest version via PicoDrive or Genesis Plus GX.

**Comment by Mikejmoffitt** [comment] 2017-03-08 23:34
Reproduced. Looks like I'm setting the priority bit for the elevator, elevator_stop, and wip objects. That should be a simple fix; the priority doesn't even make the elevator appear on top of lyle so there isn't a reason for it to be set.

**Comment by Jareth247** [comment] 2017-03-09 05:01
Alright. Eagerly awaiting the next version. I think I've gotten as far as I can in the current demo. Also, any plans for this after the game's finished? I know the source for the original's available (IDK if you're using that or simply remaking it from the ground up, but I'm glad you are porting this little-known Metroidvania), and I didn't know if you'd port the game to other systems or even work with someone to expand the original or even make a sequel.

Regardless, keep up the awesome work.

**Comment by Mikejmoffitt** [comment] 2017-03-11 22:24
Fixed in da85ad6388dd6223d89bf12368dc4c71aeb21c2e.

**Closed** 2017-03-11 22:23 UTC
